### ISSUE TITLE
Typo in example python code in README

### ISSUE THREAD

**Issue by optiz0r** [hashicorp/vault-plugin-auth-kerberos#22]
I can't get the example code to work as presented. `KRB5_TRACE` yields:
```
...
[22400] 1573930989.92876: Requesting tickets for HTTP\/vault.domain/localhost.example.com@EXAMPLE.COM, referrals on
...
kerberos.GSSError: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('Server not found in Kerberos database', 100001))
```

I believe this:
```python
service = "HTTP/vault.domain"
```
should instead be:
```python
service = "HTTP@vault.domain"
```

Which then works as expected.

Not sure if strictly required either, but my servicePrincipal is of the form `HTTP/vault.domain:8200` and therefore my `service` should actually be `HTTP@vault.domain:8200`. Since there's no release of this project yet, I'm still using winton's 1.3 release, but with this example code on in this project.

**Comment by tyrannosaurus-becks** [comment]
Hi @optiz0r - thanks for bringing that to my attention! I tested, and yes, that's the case. I used our `$ make dev` environment and I was able to log in through the Python _lower down_ in the README, which differs from above. In my test, ultimately, the service I used to successfully login was "HTTP@86bfbe14ddcb.matrix.lan:8200". To your point, it uses an @ not a /. Good catch!

**Comment by tyrannosaurus-becks** [comment]
Fixed in https://github.com/hashicorp/vault-plugin-auth-kerberos/commit/0ab7f627e23be1416416c8bc6065c60035c71ce5.
