### ISSUE TITLE
Troubleshooting with FAST

### ISSUE THREAD

**Issue by mbrancato** [hashicorp/vault-plugin-auth-kerberos#40]
I'm attempting to troubleshoot using this with AD (2016). I'm doing the following:

```
vagrant@vault01:~$ login-kerb -username=vault_svc -service="HTTP@vault" -realm="DOMAIN.LOCAL" -keytab_path=/home/vagrant/vault.keytab -krb5conf_path=/etc/krb5.conf -vault_addr="http://localhost:8200"
couldn't get auth header: couldn't log in: [Root cause: KRBMessage_Handling_Error] KRBMessage_Handling_Error: AS Exchange Error: AS_REP is not valid or client password/keytab incorrect < KRBMessage_Handling_Error: KDC did not respond appropriately to FAST negotiation
```

And that led me here: https://github.com/jcmturner/gokrb5/blob/master/USAGE.md#active-directory-kdc-and-fast-negotiation

Any idea how to enable FAST negotiation in Active Directory? I feel like documenting this is topical to this auth method. 

I have tried enabling support for "KDC support for claims, compound authentication and Kerberos armoring" under "Computer Configuration\Administrative Templates\System\KDC\" but that didn't seem to do the trick.

**Comment by mbrancato** [comment]
While I think I've done what is necessary for the KDC and Kerberos client config in AD, the FAST negotiation is still failing.

As a work around, I was able to disable it on the client end by adding `client.DisablePAFXFAST(true)` here: https://github.com/hashicorp/vault-plugin-auth-kerberos/blob/70337fca9d210037971c37f4be9695f47bd2891b/cli.go#L134

I also had to manually set my mount path here since I wasn't using the default: https://github.com/hashicorp/vault-plugin-auth-kerberos/blob/3a958d8fe521914c509fe866c8f0751b9501b9d9/cmd/login-kerb/main.go#L95

**Comment by mbrancato** [comment]
I'll leave this open for now since it doesn't seem to work with `login-kerb`, but I assume this will be replaced with `vault login -method=kerberos` when merged.

**Comment by tyrannosaurus-becks** [comment]
Thanks for opening this issue, Mike. I checked in with my team about this and we'd like to address this nearly immediately. Assigning to myself and I'll go ahead and take it on, although you're welcome to open a PR if you beat me to it.

**Comment by tyrannosaurus-becks** [comment]
Marking it as an enhancement because AD wasn't one of our tested paths for this release, but it's such a minor lift to support it that we'd like to do it.

**Comment by mbrancato** [comment]
Thanks! Sorry I didn't know the direction you wanted to go on this support, so I had just fixed locally for myself. Thanks for adding this support. I noticed the tests are all Samba based. I'm doing some more testing, I'll try to provide any support I can and contribute back.
