### ISSUE TITLE
LDAP - unable to get user binddn

### ISSUE THREAD

**Issue by mbrancato** [hashicorp/vault-plugin-auth-kerberos#41]
I'm testing this with AD and getting an error very similar to this issue from Vault: https://github.com/hashicorp/vault/issues/6325
I'm using `master` here which I think was updated with this fix a few days ago.

The error I see is the following (I have raw audit logs streaming):
```
vagrant@vault01:~$ login-kerb -username=vault_svc -service="HTTP/vault" -realm="DOMAIN.LOCAL" -keytab_path=/home/vagrant/vault.keytab -krb5conf_path=/etc/krb5.conf -vault_addr="http://localhost:8200"
{"time":"2020-02-18T15:43:55.538387088Z","type":"request","auth":{"token_type":"default"},"request":{"id":"e67634d4-cd50-838e-e648-a11d6f7aa996","operation":"update","namespace":{"id":"root"},"path":"auth/kerberos/domain.local/login","remote_address":"127.0.0.1"}}
unexpected Vault response 500: {"errors":["unable to get user binddn: LDAP search for binddn 0 or not unique"]}

{"time":"2020-02-18T15:43:55.558019575Z","type":"response","auth":{"token_type":"default"},"request":{"id":"e67634d4-cd50-838e-e648-a11d6f7aa996","operation":"update","namespace":{"id":"root"},"path":"auth/kerberos/domain.local/login","remote_address":"127.0.0.1"},"response":{},"error":"unable to get user binddn: LDAP search for binddn 0 or not unique"}
```

For reference, my config using Terraform looks like this:
```
resource "vault_generic_endpoint" "auth_kerberos_config_ldap" {
  depends_on           = [vault_generic_endpoint.auth_kerberos_config]
  path                 = "${vault_generic_endpoint.auth_kerberos_config.path}/ldap"
  ignore_absent_fields = true
  disable_delete       = true

  data_json = jsonencode({
    binddn         = "CN=vagrant-domain,CN=Users,DC=domain,DC=local"
    bindpass       = "....."
    deny_null_bind = true
    groupattr      = "cn"
    groupdn        = "DC=domain,DC=local"
    groupfilter    = "(&(objectClass=group)(member:1.2.840.113556.1.4.1941:={{.UserDN}}))"
    insecure_tls   = false
    starttls       = false
    userdn         = "DC=domain,DC=local"
    userattr       = "samaccountname"
    upndomain      = "DOMAIN.LOCAL"
    url            = "ldap://dc01.domain.local"
  })
}
```

Any thoughts on what needs to change in this config or could it be my keytab? I tried some of the suggestions on the above issue with no success. Removing the upndomain was a common suggestion, but that results in an error.

**Comment by mbrancato** [comment]
for reference, if I remove the `upndomain` I get this:
```
unexpected Vault response 400: {"request_id":"e9ce66a6-2775-43cf-01b1-e2f363de09c9","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":["identity domain of \"DOMAIN.LOCAL\" doesn't match LDAP upndomain of \"\""],"auth":null}
```

**Comment by tyrannosaurus-becks** [comment]
I've found a good method for approaching this is trying to construct an `ldapsearch` command that gets exactly 1 hit, then translating that to a Vault config. This shortens the cycle on checking which options to use and what works.

If you're able to get `ldapsearch` working for having 1 hit, and Vault isn't likewise able to use it, can you please post that command here for debugging on our end? With sensitive values replaced, of course.

**Comment by mbrancato** [comment]
Hi @tyrannosaurus-becks - that's a really good idea to use `ldapsearch`. I think this is failing in when calling the `GetUserBindDN`: https://github.com/hashicorp/vault-plugin-auth-kerberos/blob/b19d831cffac1888fd15a6b102859ed8709b7166/vendor/github.com/hashicorp/vault/sdk/helper/ldaputil/client.go#L107

I'm trying to replicate what is going on here and it actually seems to always return one result for me.
```
vagrant@vault01:~$ ldapsearch -H ldap://dc01.domain.local -D 
"CN=vault_svc,CN=Users,DC=domain,DC=local"  -w "..." -b "CN=Users,DC=domain,DC=local" -s 
sub -LLL "(samaccountname=vagrant-domain)" dn
dn: CN=vagrant-domain,CN=Users,DC=domain,DC=local

vagrant@vault01:~$ ldapsearch -H ldap://dc01.domain.local -D 
"CN=vault_svc,CN=Users,DC=domain,DC=local"  -w "..." -b "CN=Users,DC=domain,DC=local" -s 
sub -LLL "(samaccountname=vault_svc)" dn
dn: CN=vault_svc,CN=Users,DC=domain,DC=local
```

However, the default `userPrincipalName` does not work for my service account - but I do have `servicePrincipalName`. Even when I specify `samaccountname` as the `userattr`, the LDAP lookup is still using `userPrincipalName` - that just means I can't use the service account as the bind user:
```
Feb 19 12:33:05 vault01 vault[14313]: 2020-02-19T12:33:05.948Z [DEBUG] 
auth.kerberos.auth_kerberos_6270eff9.kerberos.vault-plugin-auth-kerberos: discovering user: 
filter=(userPrincipalName=vault_svc@DOMAIN.LOCAL) userdn=CN=Users,DC=domain,DC=local 
timestamp=2020-02-19T12:33:05.947Z
```

The lookup is always changing to filter with `userPrincipalName` because the `upndomain` is not empty...
https://github.com/hashicorp/vault-plugin-auth-kerberos/blob/b19d831cffac1888fd15a6b102859ed8709b7166/vendor/github.com/hashicorp/vault/sdk/helper/ldaputil/client.go#L123-L125

However, my main issue is I'm trying to authenticate computer accounts or service accounts - these don't have `userPrincipalName`. I've made a working solution (for users so far) so I'll close this, but I think the `userPrincipalName` logic will not work to authenticate computer accounts whenever the `upndomain` is set. I've removed it for now.

working solution so far:
```hcl
resource "vault_generic_endpoint" "auth_kerberos_config_ldap" {
  depends_on           = [vault_generic_endpoint.auth_kerberos_config]
  path                 = "${vault_generic_endpoint.auth_kerberos_config.path}/ldap"
  ignore_absent_fields = true
  disable_delete       = true


  data_json = jsonencode({
    url         = "ldap://dc01.domain.local"
    userdn      = "DC=domain,DC=local"
    userattr    = "cn"
    upndomain   = "DOMAIN.LOCAL"
    groupattr   = "cn"
    groupdn     = "DC=domain,DC=local"
    groupfilter = "(&(objectClass=group)(member:1.2.840.113556.1.4.1941:={{.UserDN}}))"
    binddn      = "CN=vagrant-domain,CN=Users,DC=domain,DC=local"
    bindpass    = "..."
  })
}
```
